version: "3"
services:
   mqtt:
    build: .
    container_name: "Mosquitto"
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/$USER/mosquitto/data:/mosquitto/data
      - /home/$USER/mosquitto/config:/mosquitto/config
      - /home/$USER/mosquitto/log:/mosquitto/log
    network_mode: "host"
    environment:
      - TZ=America/Chicago
